lessons:
  target: dev
  outputs:
    dev:
      dataset: dbt_lessons
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dbt-tutorial-463605
      threads: 1
      type: bigquery
    production:
      dataset: dbt_lessons
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dbt-tutorial-463605
      threads: 1
      type: bigquery
